### PR TITLE
Rebase onto upstream and use oasis-rs

### PR DESCRIPTION
**Pull request by nhynes**

### CODE REVIEW

**Comment by nhynes** [comment]
e2e tests pass. is it possible to enable force pushing onto master?

**Comment by peterjgilbert** [comment]
> e2e tests pass. is it possible to enable force pushing onto master?

Probably need @ryscheng for that. Maybe @david-yan still has admin, as I believe he created this repo?

**Review by ryscheng — CHANGES_REQUESTED** [review]
@peterjgilbert @nhynes everything has to be versioned. Please no more dependencies on git repos master branches. We must have learned our lesson by now

**Comment by peterjgilbert** [comment]
The only unversioned git dep here is https://github.com/oasislabs/owasm-abi/blob/577fd090faaba468189ff6e2ed6e8fd5a6f8a8f2/Cargo.toml#L20, which needs to be published on crates.

**Comment by nhynes** [comment]
What if I make a git tag? I don't think this crate wants to go on crates.io. As a side benefit, it means that people can't publish their contracts as crates, which is good because it won't pollute the crates.io ecosystem.

**Comment by ryscheng** [comment]
Why not go on crates?

**Comment by nhynes** [comment]
because I want

```toml
[dependencies]
oasis = "1.0.0"
```

but the `oasis` crate is taken on crates.

**Comment by ryscheng** [comment]
Why not owasm-something? This seems like an important enough decision that
we should get more input on. @peterjgilbert @armaniferrante

**Pull request closed without merging**
